name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prerequisites
      run: |
        mkdir -p ${{github.workspace}}/prerequisites
        wget --quiet https://github.com/google/googletest/archive/refs/tags/release-1.11.0.tar.gz
        tar -xvzf ${{github.workspace}}/prerequisites/release-1.11.0.tar.gz
        mkdir -p ${{github.workspace}}/prerequisites/googletest-release-1.11.0/build && cd ${{github.workspace}}/prerequisites/googletest-release-1.11.0/build && cmake .. -DCMAKE_BUILD_TYPE=Release && make install
        rm -rf ${{github.workspace}}/prerequisites
      shell: bash

    - name: Configure
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        echo "CMAKE_PROJECT_VERSION_MAJOR CMakeCache.txt | cut -d "=" -f2" >> $VERSION_MAJOR
        echo "CMAKE_PROJECT_VERSION_MINOR CMakeCache.txt | cut -d "=" -f2" >> $VERSION_MINOR
        echo "CMAKE_PROJECT_VERSION_PATCH CMakeCache.txt | cut -d "=" -f2" >> $VERSION_PATCH

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
    
    - name: Package
      working-directory: ${{github.workspace}}/build
      run: |
        cpack -G DEB
        cpack -G TGZ
        cpack -G ZIP
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}
        files: |
            *.zip
            *.tar.gz
            *.deb
